### ISSUE TITLE
Please add tag for 1.0.3 release

### ISSUE THREAD

**Issue by pravi** [thednp/dommatrix#2]
In debian we would like to build node modules from their sources. In this particular case, rollup.config.js is missing the npm registry so we can't use that. Please add 1.0.3 tag in the repo so we can use this repo as source for the debian package.

**Comment by thednp** [comment]
You mean create a new Github release tag 1.0.3?

**Comment by thednp** [comment]
There you go!

**Comment by pravi** [comment]
Thanks!

**Comment by thednp** [comment]
@pravi please have a minute to test the latest master v2.0.0-alpha1.

Install `npm install @thednp/dommatrix`. Once tested is successful we release 2.0.0 stable.

Thank you.

**Comment by pravi** [comment]
@thednp my interest in dommatrix was for packaging pdf.js. So only when pdf.js update their build dependency I will be looking at this module.

**Comment by thednp** [comment]
Cool, let me know if you need anything.
